"""
数据访问入口：若配置了环境变量 DATABASE_URL 则走 MySQL，否则沿用内存版。
"""

from api.database import db_enabled

if db_enabled():
    from api.store_mysql import (  # noqa: F401
        add_alert,
        add_blacklist,
        delete_blacklist,
        allocate_product_no,
        allocate_underwriting_case_no,
        allocate_claim_no,
        allocate_service_ticket_no,
        allocate_channel_code,
        # 规则库
        seed_preset_rules_if_empty,
        create_policy,
        create_customer,
        create_product,
        create_underwriting_case,
        create_claim,
        create_service_ticket,
        create_channel,
        delete_policy,
        delete_customer,
        delete_product,
        delete_underwriting_case,
        delete_claim,
        delete_service_ticket,
        delete_channel,
        get_policy,
        get_customer,
        get_product,
        get_conflicting_product_for_catalog_key,
        get_underwriting_case,
        get_claim,
        get_service_ticket,
        get_channel,
        list_alerts,
        list_blacklist,
        list_policies,
        list_customers,
        list_products,
        list_underwriting_cases,
        list_claims,
        list_service_tickets,
        list_channels,
        update_policy,
        update_customer,
        update_product,
        update_underwriting_case,
        update_claim,
        update_service_ticket,
        update_channel,
        update_blacklist,
    )
    from api.finance_store_mysql import (  # noqa: F401
        allocate_commission_settlement_no,
        allocate_premium_flow_no,
        create_commission_settlement,
        create_premium_flow,
        delete_commission_settlement,
        delete_premium_flow,
        get_commission_settlement,
        get_premium_flow,
        list_commission_settlements,
        list_premium_flows,
        update_commission_settlement,
        update_premium_flow,
    )
    from api.reinsurance_store_mysql import (  # noqa: F401
        allocate_reinsurance_bill_no,
        allocate_reinsurance_contract_no,
        create_reinsurance_bill,
        create_reinsurance_contract,
        delete_reinsurance_bill,
        delete_reinsurance_contract,
        get_reinsurance_bill,
        get_reinsurance_contract,
        list_reinsurance_bills,
        list_reinsurance_contracts,
        update_reinsurance_bill,
        update_reinsurance_contract,
    )
    from api.agent_store_mysql import (  # noqa: F401
        allocate_agent_no,
        allocate_agent_performance_no,
        allocate_agent_team_no,
        create_agent,
        create_agent_team,
        delete_agent,
        delete_agent_team,
        get_agent,
        get_agent_performance_summary,
        get_agent_team,
        list_agent_teams,
        list_agents,
        seed_agent_demo_data_if_empty,
        update_agent,
        update_agent_team,
    )
    from api.system_store_mysql import (  # noqa: F401
        create_system_param,
        create_system_user,
        delete_system_param,
        delete_system_user,
        get_system_param,
        get_system_user,
        list_system_logs,
        create_system_log,
        list_system_params,
        list_system_users,
        seed_system_demo_data_if_empty,
        update_system_param,
        update_system_user,
    )
else:
    from api.customer_store import (  # noqa: F401
        create_customer,
        delete_customer,
        get_customer,
        list_customers,
        update_customer,
    )
    from api.policy_store import (  # noqa: F401
        create_policy,
        delete_policy,
        get_policy,
        list_policies,
        update_policy,
    )
    from api.product_store import (  # noqa: F401
        allocate_product_no,
        create_product,
        delete_product,
        get_conflicting_product_for_catalog_key,
        get_product,
        list_products,
        update_product,
    )
    from api.risk_store import (  # noqa: F401
        add_alert,
        add_blacklist,
        delete_blacklist,
        list_alerts,
        list_blacklist,
        update_blacklist,
    )
    from api.underwriting_store import (  # noqa: F401
        allocate_case_no as allocate_underwriting_case_no,
        create_underwriting_case,
        delete_underwriting_case,
        get_underwriting_case,
        list_underwriting_cases,
        update_underwriting_case,
    )
    from api.claim_store import (  # noqa: F401
        allocate_claim_no,
        create_claim,
        delete_claim,
        get_claim,
        list_claims,
        update_claim,
    )
    from api.service_ticket_store import (  # noqa: F401
        allocate_ticket_no as allocate_service_ticket_no,
        create_service_ticket,
        delete_service_ticket,
        get_service_ticket,
        list_service_tickets,
        update_service_ticket,
    )
    from api.channel_store import (  # noqa: F401
        allocate_channel_code,
        create_channel,
        delete_channel,
        get_channel,
        list_channels,
        update_channel,
    )
    from api.finance_store import (  # noqa: F401
        allocate_commission_settlement_no,
        allocate_premium_flow_no,
        create_commission_settlement,
        create_premium_flow,
        delete_commission_settlement,
        delete_premium_flow,
        get_commission_settlement,
        get_premium_flow,
        list_commission_settlements,
        list_premium_flows,
        update_commission_settlement,
        update_premium_flow,
    )
    from api.reinsurance_store import (  # noqa: F401
        allocate_reinsurance_bill_no,
        allocate_reinsurance_contract_no,
        create_reinsurance_bill,
        create_reinsurance_contract,
        delete_reinsurance_bill,
        delete_reinsurance_contract,
        get_reinsurance_bill,
        get_reinsurance_contract,
        list_reinsurance_bills,
        list_reinsurance_contracts,
        update_reinsurance_bill,
        update_reinsurance_contract,
    )
    from api.agent_store import (  # noqa: F401
        allocate_agent_no,
        allocate_agent_performance_no,
        allocate_agent_team_no,
        create_agent,
        create_agent_team,
        delete_agent,
        delete_agent_team,
        get_agent,
        get_agent_performance_summary,
        get_agent_team,
        list_agent_teams,
        list_agents,
        update_agent,
        update_agent_team,
    )
    from api.system_store import (  # noqa: F401
        create_system_param,
        create_system_user,
        delete_system_param,
        delete_system_user,
        get_system_param,
        get_system_user,
        list_system_logs,
        create_system_log,
        list_system_params,
        list_system_users,
        update_system_param,
        update_system_user,
    )
